name:                GB1
version:             0.1.0.0
github:              "githubuser/GB1"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/GB1#readme>

dependencies:
- base-noprelude >= 4.7 && < 5
- classy-prelude

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

library:
  source-dirs: src

executables:
  GB1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GB1

tests:
  GB1-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GB1
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-hedgehog
    - hspec
    - hedgehog
